### ISSUE TITLE
Unable to use mouse button bindings for mouseover targetting on Grid2 frames

### ISSUE THREAD

**Issue by ShrikeBTR** [michaelnpsp/Grid2#91] opened 2022-11-29 17:18 UTC
Hello - currently (and this may be an old issue) it appears that abilities on toolbars, whose buttons have been bound to mouse buttons, cannot be used to target abilities while mousing over grid2 frames.

Example:
With evoker's "Verdant Embrace", if resident on a bar whose buttons are bound to 1-9, or alt+Letter (alt-A, alt-S, alt-D), and using bliz's new built-in mouseover casting, you can mouse over a grid2 target, cast, and target the moused-over person, as expected.

If that ability is moved to a bar where the bound mapping is Mouse Button 4 or 5 (or shift+ Mouse 4, or 5) - the ability can still be cast with "no target", or with a traditional click-to-set-target, but the button does not respond when mousing over grid2 frames. When mousing over players in the world, the mouse targeting works.

Version 2.0.72 Stable.

**Comment by ShrikeBTR** [comment] 2022-11-29 17:19
Also tested with traditional "Mouse over macro" config, with the same result.

**Comment by michaelnpsp** [comment] 2022-11-29 20:13
Grid2 does not manage mouse over casting, so i think i can do nothing to fix this issue.  Anyway i cannot reproduce the issue, i tested with several chaman spell,s assigned to mouseover-button1/button2/button4/button5 using blizzard clickcasting interface, and moved the same spell to an action bar button assigned to mouse button4 or  button5,  and all was working fine.

**Comment by ShrikeBTR** [comment] 2022-11-29 21:53
Ok thank you for your help! I didn't think to test with blizzard frames - I havn't used them in years because I use Grid2 instead :)

It definitely sounds like an issue for bliz. In the meantime I will try the clickcasting config. Thank you!

**Closed** 2022-11-29 21:53 UTC
